#!/usr/bin/env python3
"""
Validate DICOM files generated by Go implementation using pydicom.
"""

import sys
from pathlib import Path

try:
    import pydicom
except ImportError:
    print("Error: pydicom is not installed", file=sys.stderr)
    print("Install with: pip install pydicom", file=sys.stderr)
    sys.exit(1)


def validate_dicom_file(filepath):
    """Validate a single DICOM file and return list of errors."""
    errors = []

    try:
        ds = pydicom.dcmread(str(filepath))

        # Check required tags
        required_tags = [
            ('PatientName', 'Patient Name'),
            ('PatientID', 'Patient ID'),
            ('StudyInstanceUID', 'Study Instance UID'),
            ('SeriesInstanceUID', 'Series Instance UID'),
            ('SOPInstanceUID', 'SOP Instance UID'),
            ('Modality', 'Modality'),
            ('Rows', 'Rows'),
            ('Columns', 'Columns'),
            ('BitsAllocated', 'Bits Allocated'),
            ('PhotometricInterpretation', 'Photometric Interpretation'),
        ]

        for tag_name, description in required_tags:
            if not hasattr(ds, tag_name):
                errors.append(f"Missing required tag: {description} ({tag_name})")

        # Validate tag values
        if hasattr(ds, 'Modality'):
            if ds.Modality != 'MR':
                errors.append(f"Invalid Modality: '{ds.Modality}' (expected 'MR')")

        if hasattr(ds, 'BitsAllocated'):
            if ds.BitsAllocated != 16:
                errors.append(f"Invalid BitsAllocated: {ds.BitsAllocated} (expected 16)")

        if hasattr(ds, 'PhotometricInterpretation'):
            if ds.PhotometricInterpretation not in ['MONOCHROME1', 'MONOCHROME2']:
                errors.append(f"Invalid PhotometricInterpretation: {ds.PhotometricInterpretation}")

        # Check SOP Class UID for MR Image Storage
        if hasattr(ds, 'SOPClassUID'):
            if ds.SOPClassUID != '1.2.840.10008.5.1.4.1.1.4':
                errors.append(f"Invalid SOP Class UID: {ds.SOPClassUID} (expected MR Image Storage)")

        # Check pixel data exists
        if not hasattr(ds, 'PixelData'):
            errors.append("Missing PixelData")
        else:
            # Verify pixel data size
            if hasattr(ds, 'Rows') and hasattr(ds, 'Columns'):
                expected_size = ds.Rows * ds.Columns * 2  # 2 bytes per pixel (16-bit)
                actual_size = len(ds.PixelData)
                if actual_size != expected_size:
                    errors.append(f"Pixel data size mismatch: {actual_size} bytes (expected {expected_size})")

        # Check UIDs format (should not be empty and should contain dots)
        uid_tags = ['StudyInstanceUID', 'SeriesInstanceUID', 'SOPInstanceUID']
        for uid_tag in uid_tags:
            if hasattr(ds, uid_tag):
                uid = getattr(ds, uid_tag)
                if not uid or '.' not in uid:
                    errors.append(f"Invalid {uid_tag} format: '{uid}'")
                if len(uid) > 64:
                    errors.append(f"{uid_tag} too long: {len(uid)} chars (max 64)")

        # Check patient name format (should contain ^)
        if hasattr(ds, 'PatientName'):
            name = str(ds.PatientName)
            if '^' not in name:
                errors.append(f"Patient name should contain '^' separator: '{name}'")

    except Exception as e:
        errors.append(f"Parse error: {str(e)}")

    return errors


def main():
    if len(sys.argv) < 2:
        print("Usage: validate_dicom.py <dicom_directory>")
        print("\nValidates all DICOM files in a directory")
        print("\nExample:")
        print("  python3 validate_dicom.py test-output")
        sys.exit(1)

    dicom_dir = Path(sys.argv[1])

    if not dicom_dir.exists():
        print(f"Error: Directory '{dicom_dir}' does not exist", file=sys.stderr)
        sys.exit(1)

    # Find all DICOM files
    dicom_files = []
    for pattern in ['**/*.dcm', '**/IM*', '**/IMG*.dcm']:
        dicom_files.extend(dicom_dir.glob(pattern))

    # Remove duplicates and sort
    dicom_files = sorted(set(dicom_files))

    if not dicom_files:
        print(f"No DICOM files found in {dicom_dir}", file=sys.stderr)
        sys.exit(1)

    print(f"Validating {len(dicom_files)} DICOM files in: {dicom_dir}")
    print()

    total_errors = 0
    files_with_errors = 0

    for filepath in dicom_files:
        errors = validate_dicom_file(filepath)

        if errors:
            print(f"❌ {filepath.relative_to(dicom_dir)}:")
            for error in errors:
                print(f"   {error}")
                total_errors += 1
            files_with_errors += 1
            print()

    # Summary
    print("=" * 60)
    if total_errors == 0:
        print(f"✓ All {len(dicom_files)} DICOM files are valid!")
        return 0
    else:
        print(f"✗ Found {total_errors} errors in {files_with_errors}/{len(dicom_files)} files")
        return 1


if __name__ == '__main__':
    sys.exit(main())
